import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import { GiHamburgerMenu } from "react-icons/gi";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pocket Ledger",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistMono.variable}`}>
        <nav className="flex justify-between p-3 bg-backgroundPrimary">
          <a href="/">
            {/* Link doesn't work in this case */}
            <h1 className="text-lg text-primary font-extrabold active:text-primary/45">
              Pocket Ledger
            </h1>
          </a>
          <button>
            <GiHamburgerMenu
              size={24}
              className="text-primary active:text-primary/45"
            />
          </button>
        </nav>
        {children}
        <div className="bg-middleColor py-4">
          <footer className="bg-backgroundSecondary rounded-lg shadow mx-4">
            <div className="w-full mx-auto max-w-screen-xl p-4 md:flex md:items-center md:justify-between">
              <span className="text-sm text-primary/80 sm:text-center">
                © 2025{" "}
                <a
                  href="https://flowbite.com/"
                  className="hover:underline text-primary font-semibold"
                >
                  PocketLedger™
                </a>
                . All Rights Reserved.
              </span>
              <ul className="flex flex-wrap items-center mt-3 text-sm font-medium text-primary sm:mt-0">
                <li>
                  <a href="#" className="hover:underline me-4 md:me-6">
                    About
                  </a>
                </li>
                <li>
                  <a
                    href="https://github.com/fantasyfuerte/pocket-ledger"
                    target="_blank"
                    className="hover:underline me-4 md:me-6"
                  >
                    Repo
                  </a>
                </li>
                <li>
                  <a
                    href="https://www.instagram.com/fuerte.ts"
                    target="_blank"
                    className="hover:underline me-4 md:me-6"
                  >
                    Contact
                  </a>
                </li>
              </ul>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
