import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { GiHamburgerMenu } from "react-icons/gi";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${geistMono.variable} bg-backgroundPrimary`}>
        <nav className="flex justify-between p-5">
          <Link href="/">
            <h1 className="text-lg text-primary font-extrabold">
              Pocket Ledger
            </h1>
          </Link>
          <button>
            <GiHamburgerMenu
              size={24}
              className="text-primary hover:text-middleColor"
            />
          </button>
        </nav>
        {children}
      </body>
    </html>
  );
}
